"""add_cluster_lifecycle_states

Revision ID: b687544ab72d
Revises: d0166ce97178
Create Date: 2026-05-24 21:02:24.415076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b687544ab72d'
down_revision: Union[str, Sequence[str], None] = 'd0166ce97178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('healed_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('topic',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.alter_column('topic',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('healed_at')
        batch_op.drop_column('state')

    # ### end Alembic commands ###
