"""add_schema_baseline_and_dict_job_updates

Revision ID: d0166ce97178
Revises: d5e6f7a8b9c0
Create Date: 2026-05-24 17:04:31.051239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0166ce97178'
down_revision: Union[str, Sequence[str], None] = 'd5e6f7a8b9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dict_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('change_note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dict_jobs', schema=None) as batch_op:
        batch_op.drop_column('change_note')
        batch_op.drop_column('system')

    # ### end Alembic commands ###
